services:
  db-service:
    build: .
    image: postgis/postgis:14-3.3
    container_name: db-service
    environment:
      POSTGRES_DB: ev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql 
      - ./initdb:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - osm_network

  osm-importer:
    build:
      context: ./osm-importer
      dockerfile: Dockerfile
    container_name: osm-importer
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      PGHOST: db-service
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: ev_db
      REGION: tunisia
      DATADIR: /osm/data
    volumes:
      - ./data:/osm/data
    networks:
      - osm_network

networks:
  osm_network:

volumes:
  postgis_data: