[project]
name = "01-simple-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M.Mezni", email = "mamezni@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "weasyprint>=69.0",
]

[project.scripts]
01-simple-rag = "01_simple_rag:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
